# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'oldrel-3'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false
      # Some packages might unavailable on the older versions, so let's ignore xref warnings
      _R_CHECK_RD_XREFS_: false
      # Runs vdiffr test only on the latest version of R
      VDIFFR_RUN_TESTS: ${{ matrix.config.r == 'release' }}
      VDIFFR_LOG_PATH: "../vdiffr.Rout.fail"

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # TODO: remove this when R 4.6 is released
      - name: Tweak for old Windows (R 4.1)
        uses: r-lib/actions/setup-r-dependencies@v2
        if: ${{ matrix.config.os == 'windows-latest' && matrix.config.r == 'oldrel-4' }}
        with:
          cache-version: 3
          extra-packages: >
            any::rcmdcheck,
            ragg@1.4.0,
            Hmisc=?ignore-before-r=4.2.0,
            quantreg=?ignore-before-r=4.3.0
            local::.
          needs: check

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: ${{ matrix.config.os != 'windows-latest' || matrix.config.r != 'oldrel-4' }}
        with:
          cache-version: 3
          extra-packages: >
            any::rcmdcheck,
            Hmisc=?ignore-before-r=4.2.0,
            quantreg=?ignore-before-r=4.3.0
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'


      # > If the workflow run is a re-run, with debugging enabled, then it opens a tmate shell that you can ssh into for interactive debugging.
      # > It uses https://github.com/mxschmitt/action-tmate internally.
      # Usage:
      # * Add your SSH key to your GitHub account. This action does not work without an SSH key.
      # * If a workflow run fails, on the web UI select a re-run and turn on debug logging.
      # * Wait until the workflow output tells you that the tmate shell is ready, and copy paste the random hostname.
      # * Use ssh to log in to the VM.
      - name: Debug GHA job (tmate)
        uses: r-hub/actions/debug-shell@v1
        # Use `always()` as the action will skip its steps internally if debugging is not enabled and the workflow is not a re-run.
        if: always()
        with:
          connect-timeout-seconds: "600"
